### ISSUE TITLE
Fail to compile on the Ubuntu 16.04 due to the following error

### ISSUE THREAD

**Issue by chaoranzhang** [chaoranzhang/MitsubaToFRenderer#1]
Hi, with steps followed in the Install.txt, I cannot compile it due to the following error.

/usr/include/eigen3/Eigen/src/Core/SelfCwiseBinaryOp.h:19:28:   required from ‘Derived& Eigen::DenseBase<Derived>::operator*=(const Scalar&) [with Derived = Eigen::Matrix<DScalar1<float, Eigen::Matrix<float, 1, 7> >, 3, 1, 0, 3, 1>; Eigen::DenseBase<Derived>::Scalar = DScalar1<float, Eigen::Matrix<float, 1, 7> >]’
src/integrators/misc/motion.cpp:471:7:   required from here
/usr/include/eigen3/Eigen/src/Core/functors/AssignmentFunctors.h:88:102: error: no match for ‘operator*=’ (operand types are ‘DScalar1<float, Eigen::Matrix<float, 1, 7> >’ and ‘const DScalar1<float, Eigen::Matrix<float, 1, 7> >’)
   EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void assignCoeff(DstScalar& a, const SrcScalar& b) const { a *= b; }
                                                                                                      ^
In file included from src/integrators/misc/motion.cpp:21:0:
include/mitsuba/core/autodiff.h:252:19: note: candidate: DScalar1<_Scalar, _Gradient>& DScalar1<_Scalar, _Gradient>::operator*=(const Scalar&) [with _Scalar = float; _Gradient = Eigen::Matrix<float, 1, 7>; DScalar1<_Scalar, _Gradient>::Scalar = float]
  inline DScalar1& operator*=(const Scalar &v) {
                   ^
include/mitsuba/core/autodiff.h:252:19: note:   no known conversion for argument 1 from ‘const DScalar1<float, Eigen::Matrix<float, 1, 7> >’ to ‘const Scalar& {aka const float&}’
scons: *** [build/release/integrators/misc/motion.os] Error 1
scons: building terminated because of errors.
